/**
 * PhantomWP Dev Tools
 * Auto-managed by PhantomWP infrastructure -- do not edit this file.
 * To update: use the Infrastructure modal in the PhantomWP editor.
 */

/**
 * Vite plugin: inject data-component attributes on .astro components in dev mode
 * so the IDE element inspector can identify which component file rendered each DOM element.
 * Uses a 'load' hook to modify .astro source before Astro's own compiler sees it.
 * Only active in dev (serve) mode -- no impact on production builds.
 */
export function devComponentIdPlugin() {
    return {
        name: 'dev-component-ids',
        enforce: 'pre',
        apply: 'serve',
        async load(id) {
            if (!id.endsWith('.astro') || id.includes('?')) return null;
            const relative = id.includes('/src/') ? id.substring(id.indexOf('/src/') + 1) : null;
            if (!relative) return null;
            if (!relative.startsWith('src/components/') && !relative.startsWith('src/layouts/')) return null;

            const { readFile } = await import('node:fs/promises');
            let code;
            try { code = await readFile(id, 'utf-8'); } catch { return null; }

            if (code.includes('data-component=')) return null;

            const fmStart = code.indexOf('---');
            if (fmStart === -1) return null;
            const fmEnd = code.indexOf('---', fmStart + 3);
            if (fmEnd === -1) return null;
            const templateStart = fmEnd + 3;
            const template = code.substring(templateStart);

            const tagMatch = template.match(/(<[a-zA-Z][\w.-]*)(\s|>)/);
            if (!tagMatch) return null;

            const insertPos = templateStart + tagMatch.index + tagMatch[1].length;
            const attr = ' data-component="' + relative + '"';

            return code.substring(0, insertPos) + attr + code.substring(insertPos);
        },
    };
}
